apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: genericdaemons.mygrouop.mydomain.com
spec:
  group: mygrouop.mydomain.com
  names:
    kind: GenericDaemon
    plural: genericdaemons
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              type: string
            label:
              type: string
          required:
          - label
          - image
          type: object
        status:
          properties:
            count:
              format: int32
              type: integer
          required:
          - count
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
